express/express/urls.py
from django.views.static import serve
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from accounts.views import *
from addresses.views import upload_person_id, insert_ems_mark_view, assert_person_with_mobile_last_four, assert_tracking
from people.views import upload_person_id_view
from waybills.views import *
from pallets.views import *
from emanage.views import *
from blog.views import *
from siteconf.views import *
from waybills.views import waybills, waybill
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view
from rest_framework.authtoken import views as auth_token_views
from django.contrib.auth import views as auth_views

from express.settings import MEDIA_ROOT

schema_view = get_schema_view(title='Expresss API')

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'waybills', WaybillViewSet)
router.register(r'users', UserViewSet)
router.register(r'goods', GoodViewSet)
router.register(r'pallets', PalletViewSet)
router.register(r'waybillstatusentry', WaybillStatusEntryViewSet)
router.register(r'location', LocationViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', customer_login_view, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    # url(r'^', include('django.contrib.auth.urls')),

    # rest API
    url('^schema/$', schema_view),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^api-token-auth/$', auth_token_views.obtain_auth_token),
    url(r'^api/', include(router.urls)),
    # url(r'^api/waybill_bulk_create/$', waybill_bulk_create, name="api-bulk-create-waybill"),
    url(r'^api/waybill_bulk_create/$', waybill_bulk_create_new, name="api-bulk-create-waybill"),

    url(r'^api-ajax/waybill-checkin/$', manage_checkin_view, name='manage-check-in-ajax'),
    url(r'^api-ajax/waybill-check-form/$', manage_waybill_check_form, name='manage-waybill-form-ajax'),
    url(r'^api-ajax/waybill-detail/$', manage_waybill_detail, name='manage-waybill-detail-ajax'),
    url(r'^api-ajax/waybill-error-report-form/$', manage_waybill_error_report_form,
        name='manage-waybill-error-report-form-ajax'),
    url(r'^api-ajax/waybill-weight/$', manage_waybill_weight, name='manage-waybill-weight'),
    url(r'^api-ajax/waybill-error-report/$', manage_waybill_error_report, name='manage-waybill-error-report'),
    url(r'^api-ajax/waybill-package-to-pallet/', manage_waybill_package_to_pallet_view,
        name='manage-package-to-pallet'),
    url(r'^api-ajax/waybill-package-to-pallet2/', manage_waybill_package_to_pallet_view2,
        name='manage-package-to-pallet2'),
    url(r'^api-ajax/pallet-create/$', manage_pallet_create, name='manage-pallet-creaet-ajax'),
    url(r'^api-ajax/waybills-in-pallet-not-submit/$', get_waybills_in_pallet_not_submit,
        name='manage-waybills-in-pallet-not-submit-ajax'),
    url(r'^api-ajax/waybill-pallet-delete/(?P<pk>[0-9]+)/$', manage_waybill_pallet_delete,
        name='manage-waybill-pallet-delete'),
    url(r'^api-ajax/waybill-exist/(?P<type>[abcd])/$', manage_waybill_exist_check,
        name='manage-waybill-exist-check-ajax'),

    url(r'^api-ajax/air-waybill-create/$', manage_air_waybill_create, name='manage-air-waybill-create-ajax'),
    url(r'^api-ajax/air-waybill-send-out/(?P<pk>[0-9]+)/$', manage_air_waybill_send_out,
        name='manage-air-waybill-send-out-ajax'),
    url(r'^api-ajax/air-waybill-update-airline/(?P<pk>[0-9]+)/$', manage_air_waybill_update_airline,
        name='manage-air-waybill-update-airline-ajax'),
    url(r'^api-ajax/air-waybill-cn-deliver/(?P<pk>[0-9]+)/$', manage_air_waybill_cn_deliver,
        name='manage-air-waybill-cn-deliver-ajax'),
    url(r'^api-ajax/waybill-usps-update/$', update_waybill_usps, name='manage-waybill-usps-update-ajax'),
    url(r'^api-ajax/add-yunda/$', add_yunda_waybills, name='manage-add-yunda-ajax'),
    url(r'^api-ajax/goods/(?P<waybill_id>[0-9]+)/$', waybill_goods, name='manage-goods_detail-ajax'),

    url(r'^api-ajax/check-cn-status/$', check_cn_status_excel, name='manage-check-cn-status-ajax'),
    url(r'^api-ajax/upload-person-id/$', upload_person_id, name='manage-upload-person-id-ajax'),
    url(r'^api-ajax/assert-person/$', assert_person_with_mobile_last_four, name='manage-assert-person-ajax'),
    url(r'^api-ajax/assert-tracking/$', assert_tracking, name='manage-assert-tracking-ajax'),

    url(r'^api-ajax/get-virtual-yunda-excel/$', get_virtual_yunda_excel, name='manage-get-virtual-yunda-excel-ajax'),
    url(r'^api-ajax/update-virtual-yunda-excel/$', update_virtual_yunda_excel_view,
        name='manage-update-virtual-yunda-excel-ajax'),

    url(r'^api-ajax/mark-waybill-error/$', mark_waybill_error_view, name='manage-marl-waybill-error'),
    url(r'^api-ajax/revert-waybill-error/$', revert_waybill_error_view, name='manage-marl-waybill-error'),

    url(r'^api-ajax/get-bdt-yunda-excel/$', get_bdt_yunda_excel, name='manage-get-bdt-yunda-excel-ajax'),
    url(r'^api-ajax/get-export-q-excel/$', get_export_q_excel, name='manage-get-export-q-excel-ajax'),

    url(r'^api-ajax/get-qd-ems-excel/$', get_qd_ems_excel, name='manage-get-qd-ems-excel-ajax'),
    url(r'^api-ajax/update-cn-tracking-excel/$', update_cn_tracking_from_excel_view,
        name='manage-update-cn-tracking-excel-ajax'),
    url(r'^api-ajax/change-cn-tracking-excel/$', change_cn_tracking_from_excel_view,
        name='manage-change-cn-tracking-excel-ajax'),
    url(r'^api-ajax/change-channel-excel/$', change_channel_from_excel_view,
        name='manage-change-channel-excel-ajax'),
    url(r'^api-ajax/change-name-excel/$', change_name_from_excel_view,
        name='manage-change-name-excel-ajax'),
    url(r'^api-ajax/waybills-time/$', waybills_time,
        name='manage-waybills-time-ajax'),
    url(r'^api-ajax/waybills-send-days/$', waybills_send_days,
        name='manage-waybills-send-days-ajax'),
    url(r'^api-ajax/auto-create/$', auto_create_view, name='manage-auto-create-ajax'),

    url(r'^api-ajax/update-package-weight-excel/$', update_package_weight_from_excel_view,
        name='manage-update-package-weight-excel-ajax'),
    url(r'^api-ajax/get-labels/$', get_labels, name='manage-get-labels-ajax'),
    url(r'^api-ajax/get-waybills-cn-tracking/$', get_waybills_cn_tracking, name='manage-get-waybills-cn-tracking-ajax'),
    url(r'^api-ajax/get-waybills-bulk-print/$', manage_waybill_bulk_print_view,
        name='manage-get-waybills-bulk-print-ajax'),

    url(r'^api-ajax/insert-ems-mark-excel/$', insert_ems_mark_view, name='manage-insert-ems-mark-excel-ajax'),
    url(r'^api-ajax/bulk-print-sku/$', manage_batch_print_sku, name='manage-bulk-print-sku-ajax'),

    url(r'^api-ajax/air-waybill-fee/$', air_waybill_fee_excel_view, name='manage-air-waybill-fee-excel-ajax'),

    url(r'^api-ajax/test/$', test_api_post, name='manage-check-in-ajax'),

    url(r'^api-ajax/add-exception-record/$', manage_add_exception_record, name='manage-add-exception-record-ajax'),
    url(r'^api-ajax/get-exception-record-images/$', manage_get_exception_record_images,
        name='manage-get-exception-record-images-ajax'),
    url(r'^api-ajax/waybill-send-to-warehouse/$', waybill_send_to_warehouse,
        name='manage-waybill-send-to-warehouse-ajax'),
    url(r'^api-ajax/sifang_pdf/$', get_sifang_pdf, name='sifang-pdf-ajax'),
    url(r'^api-ajax/get-k-no-pic-excel/$', get_k_no_pid_excel, name='k-no-pic-ajax'),
    url(r'^api-ajax/import-waybill-excel/$', import_waybill_excel_view, name='import-waybill-excel'),

    # app
    url('^$', IndexView.as_view(), name='index'),
    url(r'^accounts/profile/$', customer_profile_view, name='accounts_profile'),
    url(r'^waybills/$', waybills, name='customer_waybill_list'),
    url(r'^waybills/(?P<pk>[0-9]+)/$', waybill, name='customer_waybill_detail'),
    url(r'^waybills/create/$', waybillCreate, name='customer_waybill_create'),
    url(r'^waybills/bulk_create/$', waybillBulkCreate, name='customer_waybill_bulk_create'),
    url(r'^waybills/search/$', waybill_search_view, name='customer_waybill_search'),
    url(r'^waybills/print/(?P<pk>[0-9]+)/$', WaybillPDF.as_view(), name='customer_waybill_print'),
    url(r'^waybills/label/(?P<pk>[0-9]+)/$', WaybillLabel.as_view(), name='customer_waybill_label'),
    url(r'^waybills/small_label/(?P<pk>[0-9]+)/$', WaybillSmallLabel.as_view(), name='customer_waybill_small_label'),

    url(r'^manage/$', manage_index_view, name='manage-index'),
    url(r'^manage/performance/$', performacne_view, name='manage-performance'),
    url(r'^manage/package-time/$', package_time_view, name='manage-package-time'),
    url(r'^manage/login/$', manage_login_view, name='manage-login'),
    url(r'^manage/accounts/profile/$', manage_profile_view, name='manage-account'),
    url(r'^manage/logout/$', manage_logout_view, name='manage-logout'),
    url(r'^manage/check-in-package/$', manage_waybill_check_in_view, name='manage-waybill-check-in'),
    url(r'^manage/waybill-audit/$', manage_waybill_audit_view, name='manage-waybill-audit'),
    url(r'^manage/waybill-error-report/$', manage_waybill_error_view, name='manage-waybill-error-report'),
    url(r'^manage/pallets/create/$', manage_pallet_create_view, name='manage-pallet-create'),
    url(r'^manage/pallets/create2/$', manage_pallet_create_view2, name='manage-pallet-create2'),
    url(r'^manage/waybills/$', manage_waybills_view, name='manage-waybills'),
    url(r'^manage/waybills/print-single/$', manage_waybill_print_single_good_view,
        name='manage-waybills-print-single-good'),
    url(r'^manage/waybills/print-multi/$', manage_waybill_print_multi_goods_view,
        name='manage-waybills-print-multi-goods'),
    url(r'^manage/waybills/print-tracking/$', manage_waybill_print_tracking_view,
        name='manage-waybills-print-tracking'),

express/waybills/urls.py
from django.conf.urls import url, include

urlpatterns = [
    # url(r'^create/$', waybill_create_view, name='create')
]

express/waybills/forms.py
# -*- coding: utf-8 -*
from django import forms

from .models import *

from django.forms import inlineformset_factory, ModelForm

from django.db.models import Model

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from django.db.models import Q

class WaybillSearchForm(forms.Form):
    tracking_no = forms.CharField(label=u'国际运单号', max_length=100, required=False)
    recv_name = forms.CharField(label=u'收件人', max_length=100, required=False)
    status = forms.ModelChoiceField(WaybillStatusEntry.objects.all().order_by("order_index"),empty_label=u'状态', to_field_name="order_index", required=False)
    per_page = forms.IntegerField(label=u'每页显示个数', max_value=100, required=False)

    def __init__(self, *args, **kwargs):
        super(WaybillSearchForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "form-inline"
        self.helper.field_template = "bootstrap3/layout/inline_field.html"
        self.helper.form_method = "get"
        self.helper.form_action = "customer_waybill_list"
        self.helper.layout = Layout(
            'tracking_no',
            'recv_name',
            'status',
            'per_page',
            Submit('', u'筛选'),
        )

    def addQuery(self, qs):
        if self.is_valid():
            tracking_no = self.cleaned_data["tracking_no"]
            recv_name = self.cleaned_data["recv_name"]
            status = self.cleaned_data["status"]

            q = Q()
            if tracking_no:
                q.add(Q(tracking_no__icontains=tracking_no), Q.AND)
            if recv_name:
                q.add(Q(recv_name__icontains=recv_name), Q.AND)
            if status:
                q.add(Q(status_order_index=status.order_index), Q.AND)
            return qs.filter(q)

class WaybillBatchActionForm(forms.Form):
    print_waybill = forms.ChoiceField(choices=(('','---------'),('1',u'批量打印')), required=False)

    def __init__(self, *args, **kwargs):
        super(WaybillBatchActionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "form-inline"
        self.helper.field_template = "bootstrap3/layout/inline_field.html"
        self.helper.form_method = "post"
        self.helper.form_action = "customer_waybill_list"
        self.helper.layout = Layout(
            'print_waybill',
            Submit('', u'执行'),
        )


class WaybillForm(ModelForm):
    # 省市区
    recv_province = forms.CharField(widget=forms.HiddenInput, required=True)
    recv_city = forms.CharField(widget=forms.HiddenInput, required=True)
    recv_area = forms.CharField(widget=forms.HiddenInput, required=True)
    order_no = forms.CharField(label=u'自定义单号', required=False)
    remark = forms.CharField(label=u'备注', required=False)

    recv_name = forms.CharField(label=u'收件人姓名', required=True)
    recv_address = forms.CharField(label=u'收件人地址', required=True)
    recv_zipcode = forms.CharField(label=u'收件人邮编', required=True)
    recv_mobile = forms.CharField(label=u'收件人手机', required=True)
    recv_phone = forms.CharField(label=u'电话', required=False)

    send_name = forms.CharField(label=u'发件人姓名', required=True)
    send_mobile = forms.CharField(label=u'发件人电话', required=True)
    send_address = forms.CharField(label=u'发件人地址', required=True)

    weight = forms.DecimalField(widget=forms.HiddenInput(), required=False)
    tracking_no = forms.CharField(widget=forms.HiddenInput(attrs={"style": 'display:none;'}), required=False)

    class Meta:
        model = Waybill
        fields = ['recv_province', 'recv_city', 'recv_area', 'recv_address', 'recv_zipcode', 'recv_name', 'recv_mobile',
                  'recv_phone', 'order_no', 'remark', 'send_name', 'send_mobile', 'send_address', 'weight',
                  'tracking_no']

    def __init__(self, *args, **kwargs):
        super(WaybillForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-2'
        self.helper.field_class = 'col-md-8'
        self.helper.form_tag = False
        self.helper.layout = Layout(
            'recv_province', 'recv_city', 'recv_area', 'recv_address', 'recv_zipcode', 'recv_name', 'recv_mobile',
            'recv_phone', 'order_no', 'remark', 'send_name', 'send_mobile', 'send_address',
        )


class UploadFileForm(forms.Form):
    file = forms.FileField(label="运单文件", widget=forms.FileInput(attrs={"accept": ".xls,.xlsx"}))

    def __init__(self, *args, **kwargs):
        super(UploadFileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'file',
            Submit('submit', u'导入'),
        )

class GoodForm(ModelForm):
    class Meta:
        model = Good
        fields = ['cat1', 'cat2', 'brand', 'description', 'quantity', 'unit_price','unit_weight', 'remark']

express/templates/waybills/customer_base.html
{% extends "base_v2.html" %}
{% load static %}

express/templates/waybills/waybill_buld_create.html
{% extends "waybills/customer_base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <a href='{%  static 'xls/example.xls' %}'>模板文件（请在该文件的基础上进行编辑）</a>
    {% crispy form %}

    {% if excel_error  %}
    {% endif %}
{% endblock %}

express/templates/waybills/waybill_detail.html
{% extends "waybills/customer_base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_utils %}
{% load crispy_forms_field %}

{% block css %}
{% endblock %}

{% block content %}
{#    {% include "bootstrap/table_inline_formset.html" %}#}

    <form id="myForm" method="post" action="" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_order_no" class="control-label col-md-2">
                省市区
            </label>
            <div id="distpicker2" class="controls col-md-8" data-placeholder="false">
                <select id="pro" class="form-control"></select>
                <select id="city" class="form-control"></select>
                <select id="area" class="form-control"></select>
            </div>

        </div>
{#        {{ form | crispy }}#}
        {% crispy form form.helper %}
        {{ formset.management_form }}

        <table{% if form_id %} id="{{ form_id }}_table"{% endif %} class="table table-striped table-condensed">
            <thead>
            {% if formset.readonly and not formset.queryset.exists %}
            {% else %}
                <tr>
                    {% for field in formset.forms.0 %}
                        {% if field.label and not field.is_hidden %}
                            <th style="text-align: left" for="{{ field.auto_id }}"
                                class="control-label {% if field.field.required and not field|is_checkbox %}requiredField{% endif %}">
                                {{ field.label|safe }}{% if field.field.required and not field|is_checkbox %}
                                    <span class="asteriskField">*</span>{% endif %}
                            </th>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endif %}
            </thead>

            <tbody>
            {% for form in formset %}
                {% if form_show_errors and not form.is_extra %}
                    {% include "bootstrap/errors.html" %}
                {% endif %}

                <tr>
                    {% for field in form %}
                        {% include 'bootstrap/field.html' with tag="td" form_show_labels=False %}
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <input type="submit" value="提交"/>
    </form>
{% endblock %}

{% block scripts %}
    <script src='{% static "js/jquery.formset.js" %}'></script>
    <script src='{% static "js/distpicker.min.js" %}'></script>
    <script>
        $(function () {
            $('#myForm tbody tr').formset({
                prefix: '{{ formset.prefix }}',
                addText:"+",
                deleteText:"X"
            });

            locVals = [$('#id_recv_province').val(), $('#id_recv_city').val(), $('#id_recv_area').val()]


            $("#distpicker2").distpicker({
                province: locVals[0],
                city: locVals[1],
                district: locVals[2]
            });

            $("#distpicker2 select").change(function () {
                new_val = $(this).val();
                ele_id = $(this).attr("id");
                if (ele_id == "pro") {
                    $("#id_recv_province").val(new_val);
                    $("#id_recv_city").val($("#city").val());
                    $("#id_recv_area").val($("#area").val());

                } else if (ele_id == "city") {
                    $("#id_recv_city").val(new_val);
                    $("#id_recv_area").val($("#area").val());
                } else {
                    $("#id_recv_area").val(new_val);
                }
            })

            $("#pro").trigger("change")
        })
    </script>
{% endblock %}

express/templates/waybills/waybill_list.html
{% extends "waybills/customer_base.html" %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}
{% load static %}

{% block css %}
    <style type="text/css">
        .delete > a {
            color: red
        }
    </style>

{% endblock css %}


{% block content %}

    {% crispy form form.helper %}

    {% crispy form_action %}

    {% render_table table %}


    <div class="modal" id="delete_modal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <h5 id="delete_modal_text" style="text-align: center"></h5>
                    <p id="delete_modal_fail_message" style="display: none; color: red;"></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button id="delete_modal_confirm" type="button" class="btn btn-danger">确认删除吗</button>
                    <input id="delete_modal_url" type="hidden" value="">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src='{% static "js/utils1017.js" %}'></script>
    <script>
        $(function () {
            ajaxSetup();
            var delete_modal =$('#delete_modal');

            delete_modal.modal('hide');

            $('.delete > a').click(function (e) {
                e.preventDefault();
                tracking_no = $(this).closest("tr").find(".tracking_no").text();
                delete_url = $(this).closest("tr").find(".delete>a").attr("href");

                $('#delete_modal_url').val(delete_url);
                $('#delete_modal_text').html("确认要删除运单：<strong>" + tracking_no + "</strong>?");
                $('#delete_modal_fail_message').text("");
                delete_modal.modal('show');

                return false
            });

            $("#delete_modal_confirm").click(function () {
                var delete_url = $('#delete_modal_url').val();
                {#                var csrftoken = getCookie('csrftoken');#}

                $.ajax({
                    url: delete_url,
                    method: 'Delete',
                    success: function () {
                        console.log("delete success");
                        delete_modal.modal("hide");
                        location.reload();
                    },
                    error: function (res) {
                        console.log(res["responseJSON"].detail);
                        $("#delete_modal_fail_message").text("删除失败：  " + res["responseJSON"].detail);
                        $("#delete_modal_fail_message").show()
                    }

                })
            });

            $('.printBtn > a').each(function () {
                $(this).attr('target', '_blank')
            });


            // checkbox all select or deselect
            select_all_populate();

        });
    </script>
{% endblock %}

express/templates/waybills/waybill_search.html
{% extends base_template %}
{% load static %}
{% load tz %}


{% block css %}
    <style type="text/css">

    </style>

{% endblock css %}


{% block content %}
    <div class="row">
        <div class="col-sm-8 col-sm-push-2">
            {% if manage %} <p> 您所在的时区: {{ current_timezone }}, 以下时间为您所在时区的时间 {% endif %}
            </p>
            <table class="table table-striped table-hover">
                <tbody>
                {% for waybill in data.waybills %}
                    {% if waybill.is_error and not manage %}
                        <tr class="danger">
                            <th colspan="2">运单 {{ waybill.tracking_no }} 状态异常</th>
                        </tr>
                    {% elif waybill.status_set|length > 0 %}
                        <tr class="success">
                            <th colspan="2">运单 {{ waybill.tracking_no }} 信息如下
                                {% if waybill.is_overtime %}
                                    <small style="color: red"><i class="fa fa-exclamation-triangle"></i> 如物流长时间未更新,
                                        请联系客服
                                    </small> {% endif %}
                            </th>
                        </tr>
                        {% if waybill.lack_person_id_pic %}
                            <tr>
                                <td colspan="2">该包裹缺少身份证正反面照片, 无法清关, 请补交
                                    <a href="/u/?m={{ waybill.tracking_no }}" class="btn btn-success btn-sm">
                                        <i class="fa fa-upload"></i>自助上传</a>
                                </td>
                            </tr>
                        {% else %}
                            {% if waybill.has_person_id and waybill.person_id_update_dt %}
                                <tr>
                                    <td colspan="2">顾客上传身份证时间: {{ waybill.person_id_update_dt }}</td>
                                </tr>
                            {% endif %}
                        {% endif %}
                        {% for status in waybill.status_set %}
                            <tr>
                                <td>{{ status.create_dt }}</td>
                                <td>{{ status.status__name }}
                                    {% if manage and status.remark %} 备注: {{ status.remark }} {% endif %}
                                    {% if not waybill.has_person_id and '已建单' in status.status__name and not waybill.lack_person_id_pic %}
                                        ,待收件人上传身份证
                                        <a href="/u/?m={{ waybill.tracking_no }}" class="btn btn-success btn-sm">
                                            <i class="fa fa-upload"></i>自助上传</a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr class="danger">
                            <th colspan="2">运单 {{ waybill.tracking_no }} 没有查询到运单信息</th>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block footer %}{% include "controls/footer.html" %}{% endblock %}